package:
  name: archer-avlwrapper
  version: {{ VERSION }}

source:
  path: ..

build:
  noarch: python
  script: ${PYTHON} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools_scm
  run:
    - python
    - numpy
    - matplotlib

test:
  source_files:
   - tests
  imports:
   - avlwrapper
  requires:
    - pytest
  commands:
    - pytest -v .
